const ABSENCE_DB_VERSION=1;
function profileId(){try{const p=JSON.parse(localStorage.getItem('ticket.active-profile.v2')||'null');return String(p?.id||p?.cpfHash?.slice(0,24)||'default').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80)||'default'}catch{return'default'}}
function dbName(){return`ticket-absence-db-${profileId()}`}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(dbName(),ABSENCE_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('absences')){const s=db.createObjectStore('absences',{keyPath:'id'});s.createIndex('date','date',{unique:false})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putAbsence(item){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('absences','readwrite');tx.objectStore('absences').put(item);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function listAbsences(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('absences','readonly');const r=tx.objectStore('absences').getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>`${b.date}${b.startTime}`.localeCompare(`${a.date}${a.startTime}`)));r.onerror=()=>reject(r.error)})}
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const nowTime=()=>{const d=new Date();return`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
const br=d=>{if(!d)return'';const[y,m,day]=d.split('-');return`${day}/${m}/${y}`};
function toast(t){const e=document.createElement('div');e.className='absence-toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)}
function ensureModal(){if(document.querySelector('#absenceModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="absence-modal" id="absenceModal" hidden><section class="absence-card" role="dialog" aria-modal="true" aria-labelledby="absenceTitle"><div class="absence-head"><div><h2 id="absenceTitle">Registrar ausência</h2><p>Registre o período fora da empresa e, se necessário, fotografe o documento comprobatório.</p></div><button class="absence-close" type="button" aria-label="Fechar">×</button></div><form class="absence-form" id="absenceForm"><div class="absence-grid"><label class="absence-field"><span>Data</span><input id="absenceDate" type="date" required></label><label class="absence-field"><span>Motivo</span><select id="absenceReason" required><option value="Consulta médica">Consulta médica</option><option value="Exame">Exame</option><option value="Atestado médico">Atestado médico</option><option value="Compromisso autorizado">Compromisso autorizado</option><option value="Outro">Outro</option></select></label><label class="absence-field"><span>Início da ausência</span><input id="absenceStart" type="time" required></label><label class="absence-field"><span>Fim da ausência</span><input id="absenceEnd" type="time" required></label></div><label class="absence-field"><span>Observação (opcional)</span><textarea id="absenceNote" maxlength="400" placeholder="Ex.: consulta no Hospital..."></textarea></label><label class="absence-photo"><strong>Documento comprobatório (opcional)</strong><div><small>Fotografe atestado, declaração, comprovante de consulta ou outro documento.</small></div><input id="absencePhoto" type="file" accept="image/*" capture="environment"><img id="absencePreview" class="absence-preview" alt="Prévia do documento"></label><div class="absence-actions"><button class="absence-btn secondary" type="button" data-absence-list>Ver registros</button><button class="absence-btn primary" type="submit">Salvar ausência</button></div></form><div id="absenceList" class="absence-list"></div></section></div>`);const m=document.querySelector('#absenceModal');m.querySelector('.absence-close').onclick=()=>m.hidden=true;m.addEventListener('click',e=>{if(e.target===m)m.hidden=true});document.querySelector('#absencePhoto').addEventListener('change',e=>{const f=e.target.files?.[0],img=document.querySelector('#absencePreview');if(img.dataset.url)URL.revokeObjectURL(img.dataset.url);if(f){const u=URL.createObjectURL(f);img.src=u;img.dataset.url=u;img.classList.add('show')}else img.classList.remove('show')});m.querySelector('[data-absence-list]').onclick=renderList;document.querySelector('#absenceForm').addEventListener('submit',saveAbsence)}
async function saveAbsence(e){e.preventDefault();const date=document.querySelector('#absenceDate').value,startTime=document.querySelector('#absenceStart').value,endTime=document.querySelector('#absenceEnd').value;if(endTime<=startTime){toast('O horário de saída deve ser posterior ao início da ausência.');return}const file=document.querySelector('#absencePhoto').files?.[0]||null;const item={id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,date,startTime,endTime,reason:document.querySelector('#absenceReason').value,note:document.querySelector('#absenceNote').value.trim(),document:file?{blob:file,name:file.name||'comprovante.jpg',type:file.type||'image/jpeg'}:null,createdAt:new Date().toISOString()};await putAbsence(item);toast('Ausência registrada com sucesso. Ao retornar, registre seu ponto normalmente.');e.target.reset();document.querySelector('#absencePreview').classList.remove('show');document.querySelector('#absenceDate').value=today();document.querySelector('#absenceStart').value=nowTime();await renderList();augmentHistory()}
async function renderList(){const target=document.querySelector('#absenceList');if(!target)return;const items=await listAbsences();if(!items.length){target.innerHTML='<div class="absence-empty">Nenhuma ausência registrada.</div>';return}target.innerHTML=items.slice(0,20).map(x=>`<article class="absence-item"><span class="absence-tag">${esc(x.reason)}</span><strong>${br(x.date)} • ${esc(x.startTime)} às ${esc(x.endTime)}</strong>${x.note?`<small>${esc(x.note)}</small>`:''}${x.document?'<small>📎 Documento comprobatório anexado</small>':''}</article>`).join('')}
function openAbsence(){ensureModal();const m=document.querySelector('#absenceModal');document.querySelector('#absenceDate').value=today();document.querySelector('#absenceStart').value=nowTime();document.querySelector('#absenceEnd').value='';m.hidden=false;renderList()}
function addLaunchButton(){const buttons=[...document.querySelectorAll('button')];if(buttons.some(b=>b.dataset.absenceLaunch))return;const env=buttons.find(b=>/registrar ambiente/i.test(b.textContent||''));const point=buttons.find(b=>/registrar ponto/i.test(b.textContent||''));const anchor=env||point;if(!anchor)return;const b=anchor.cloneNode(false);b.type='button';b.dataset.absenceLaunch='1';b.classList.add('absence-launch');b.innerHTML='🩺 <span>Registrar Ausência</span>';b.onclick=openAbsence;anchor.insertAdjacentElement('afterend',b)}
async function augmentHistory(){const heading=[...document.querySelectorAll('h1,h2,h3')].find(h=>/histórico diário/i.test(h.textContent||''));if(!heading)return;let panel=document.querySelector('#absenceHistoryPanel');if(!panel){panel=document.createElement('section');panel.id='absenceHistoryPanel';panel.className='absence-history-panel';heading.parentElement?.insertAdjacentElement('afterend',panel)}const items=await listAbsences();panel.innerHTML=`<h3>Ausências registradas</h3>${items.length?items.slice(0,15).map(x=>`<div class="absence-history-row"><b>${br(x.date)} • ${esc(x.startTime)} às ${esc(x.endTime)} — ${esc(x.reason)}</b><small>${x.document?'Documento anexado • ':''}${esc(x.note||'Sem observação')}</small></div>`).join(''):'<div class="absence-empty">Nenhuma ausência registrada.</div>'}`}
function syncUi(){addLaunchButton();augmentHistory()}
ensureModal();syncUi();new MutationObserver(()=>{clearTimeout(window.__absenceUiTimer);window.__absenceUiTimer=setTimeout(syncUi,80)}).observe(document.querySelector('#app')||document.body,{childList:true,subtree:true});
